# Formatting the values within a table

```{r setup, include=FALSE, echo=FALSE}
library(gt)
```

*** General introduction to the formatting pipeline

## Basic number formatting

*** General introduction to basic number formatting

### `fmt_number()`

Number-based formatting in a **gt** table can be generally performed with the `fmt_number()` function. With this any targeted, numeric values can be rendered with a higher consideration for tabular presentation. What this means is that we have fine control over how numbers are going to appear, and here are some of the main features available in the function:

- choice of the number of decimal places, option to drop trailing zeros, and a choice of the decimal symbol

- the option to enable/disable digit separators and also to choose the separator symbol

- we can choose to scale targeted values by a multiplier value

- compact numbers: larger figures (thousands, millions, etc.) can be autoscaled and decorated with the appropriate suffixes

- with a text pattern, the formatted values can be decorated with literal characters

- locale-based formatting: providing a locale ID will result in number formatting specific to the chosen locale


### `fmt_integer()`


### `fmt_percent()`



## Scientific and engineering formats

*** General introduction to scientific and engineering number formatting

### `fmt_scientific()`


### `fmt_engineering()`



## Formatting numbers to currencies and various other units

*** General introduction to currency and other symbol-adding formatting functions

### `fmt_currency()`


### `fmt_bytes()`


### `fmt_partsper()`



## Translating numbers to other forms

*** General introduction to formatting whole numbers to different textual representations

### `fmt_index()`


### `fmt_roman()`


### `fmt_num_spelled()`



## Date, time, and duration formats

*** General introduction to formatting as dates, times, and durations

### `fmt_date()`


### `fmt_time()`


### `fmt_datetime()`


### `fmt_duration()`



## Formatting with Markdown, creating links, adding images


### `fmt_markdown()`


### `fmt_url()`


### `fmt_image()`



## Creating your own formatter


### `fmt()`


## Substitution Functions


### `sub_missing()`


### `sub_zero()`


### `sub_small_vals()`


### `sub_large_vals()`


### `sub_values()`


## Text transformations


### `text_replace()`


### `text_case_when()`


### `text_case_match()`


### `text_transform()`

